//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kitaptakipapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplarim
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Page { get; set; }
        public string Kind { get; set; }
        public string Writer { get; set; }
    }
}
